version: '3'
services:
  logspout:
    image: gliderlabs/logspout:latest
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command: syslog+udp://syslogng:514
  syslogng:
    image: balabit/syslog-ng:latest
    restart: always
    command: -F --no-caps
    volumes:
      - "/logs/:/var/log/syslogng/"
      - "./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf"
      # - "./rotate_and_flush.sh:/etc/cron.hourly/rotate_and_flush.sh"
      - "./syslogng-logratate.conf:/etc/logrotate.d/syslogng-logratate.conf"
