version: '3'
services:
  logspout:
    image: gliderlabs/logspout:latest
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command: syslog+udp://syslogng:514
  syslogng:
    image: balabit/syslog-ng:latest
    restart: always
    entrypoint: /syslogng/init.sh
    command: -F --no-caps
    volumes:
      - "./syslogng:/syslogng"
      - "/logs:/var/log/syslogng"
      # - "./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf"
      # - "./rotate_and_flush.sh:/etc/cron.hourly/rotate_and_flush.sh"
      # - "./syslogng-logrotate.conf:/etc/logrotate.d/syslogng-logrotate.conf"
